---
apiVersion: v1
kind: ConfigMap
metadata:
  name: copilot-extensions
  labels:
    controller.devfile.io/mount-to-devworkspace: 'true'
    controller.devfile.io/watch-configmap: 'true'
  annotations:
    controller.devfile.io/mount-as: env
data:
  VSCODE_TRUSTED_EXTENSIONS: 'github.copilot,github.copilot-chat'
