### OpenShift Logging v6
---
apiVersion: observability.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
spec:
  managementState: Managed
  collector:
    tolerations:
    - operator: Exists
  serviceAccount:
    name: logcollector
  filters:
  - name: ocp-labels
    type: openshiftLabels
    openshiftLabels:
      cluster_name: "ocp4-dev"
  - name: mgmt-filters
    type: prune
    prune:
      in: [.userAgent, .level, .openshift.cluster_id, .k8s_audit_level, .apiVersion, .auditID, .requestReceivedTimestamp, .requestURI, .user.extra."authentication.kubernetes.io/pod-uid", .user.groups, .user.uid, .sourceIPs, .source_type, .kubernetes.container_name, .kubernetes.namespace_name, .kubernetes.pod_name]

  inputs: 
  - name: APPLICATION

  outputs:
  - name: OUTPUT

  pipelines:
  - name: audit
    inputRefs: 
    - audit
    outputRefs: 
    - OUTPUT
    filterRefs: ["ocp-labels","mgmt-filters"]
