apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: alert-binding
spec:
  params:
    - name: alertname
      value: "$(body.alerts[0].labels.alertname)"
    - name: instance
      value: "$(body.alerts[0].labels.instance)"
    - name: summary
      value: "$(body.alerts[0].annotations.summary)"
