apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: build-pipeline-
spec:
  pipelineRef:
    name: build-pipeline
  workspaces:
    - name: ssh-creds
      secret:
        secretName: ssh-auth
    - name: build
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Mi
