apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: buildah
spec:
  params:
    - name: image
      description: Reference of the image buildah will produce.
    - name: STORAGE_DRIVER
      description: Set buildah storage driver
      default: overlay
    - name: dockerfile_path 
      description: "Path to the Dockerfile to build. If repo has multiple directories for builds, give full path to the Dockerfile: path/to/Dockerfile"
      default: Dockerfile
  workspaces:
    - name: builder
  steps:
    - name: build
      image: quay.io/containers/buildah:v1.23.1
      workingDir: $(workspaces.builder.path)
      securityContext:
        privileged: true
      script: |
        buildah --storage-driver=$(params.STORAGE_DRIVER) build --no-cache -f $(params.dockerfile_path) -t $(params.image) .
      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers
    - name: push
      image: quay.io/containers/buildah:v1.23.1
      workingDir: $(workspaces.builder.path)
      securityContext:
        privileged: true
      script: |
        buildah --storage-driver=$(params.STORAGE_DRIVER) push --authfile /tmp/authfile/auth $(params.image)
      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers
        - name: image-secret
          mountPath: /tmp/authfile
  volumes:
    - name: varlibcontainers
      emptyDir: {}
    - name: image-secret
      secret:
        secretName: image-pull-secret
        items:
          - key: .dockerconfigjson
            path: auth
