apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-pipeline
spec:
  workspaces:
    - name: build
    - name: ssh-creds
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: ssh-directory
          workspace: ssh-creds
        - name: output
          workspace: build
      params:
        - name: url
          value: git@github.com:KyWa/dockerbuilds.git
        - name: deleteExisting
          value: "true"
    - name: build
      taskRef:
        name: buildah
      runAfter:
        - fetch-repository
      params:
        - name: image
          value: quay.io/kywa/go-env
        - name: dockerfile_path
          value: go-env
      workspaces:
        - name: builder
          workspace: build
