apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Secret
  metadata:
    name: mariadb
  stringData:
    password: password
    db_name: testdb
- apiVersion: v1
  kind: Service
  metadata:
   name: mariadb
  spec:
    type: ClusterIP
    ports:
    - port: 3306
      targetPort: 3306
    selector:
      app: mariadb
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: mariadb
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: mariadb
    name: mariadb
  spec:
    selector:
      matchLabels:
        app: mariadb
    replicas: 1
    template:
      metadata:
        labels:
          app: mariadb
      spec:
        containers:
        - env:
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mariadb
                key: password
          - name: MARIADB_DATABASE
            valueFrom:
              secretKeyRef:
                name: mariadb
                key: db_name
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mariadb
                key: password
          image: docker.io/mariadb:latest
          imagePullPolicy: Always
          ports:
          - name: mysql
            containerPort: 3306
            protocol: TCP
          name: mariadb
          volumeMounts:
          - mountPath: /var/lib/mysql
            name: db
        volumes:
        - name: db
          persistentVolumeClaim:
            claimName: mariadb
- apiVersion: v1
  kind: Service
  metadata:
   name: flaskapp
  spec:
    type: ClusterIP
    ports:
    - port: 8080
      targetPort: 8080
    selector:
      app: flaskapp
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: flaskapp
    name: flaskapp
  spec:
    selector:
      matchLabels:
        app: flaskapp
    replicas: 1
    template:
      metadata:
        labels:
          app: flaskapp
      spec:
        containers:
        - env:
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mariadb
                key: password
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: mariadb
                key: db_name
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mariadb
                key: password
          image: docker.io/unixislife/flask-mariadb:latest
          imagePullPolicy: Always
          name: flaskapp
          ports:
          - name: http
            containerPort: 8080
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 2
            periodSeconds: 30
            failureThreshold: 3
- apiVersion: v1
  kind: Secret
  metadata:
    name: mariadb
  stringData:
    password: password
    db_name: testdb
- apiVersion: v1
  kind: Service
  metadata:
   name: mariadb
  spec:
    type: ClusterIP
    ports:
    - port: 3306
      targetPort: 3306
    selector:
      app: mariadb
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: mariadb
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: mariadb
    name: mariadb
  spec:
    selector:
      matchLabels:
        app: mariadb
    replicas: 1
    template:
      metadata:
        labels:
          app: mariadb
      spec:
        containers:
        - env:
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mariadb
                key: password
          - name: MARIADB_DATABASE
            valueFrom:
              secretKeyRef:
                name: mariadb
                key: db_name
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mariadb
                key: password
          image: docker.io/mariadb:latest
          imagePullPolicy: Always
          ports:
          - name: mysql
            containerPort: 3306
            protocol: TCP
          name: mariadb
          volumeMounts:
          - mountPath: /var/lib/mysql
            name: db
        volumes:
        - name: db
          persistentVolumeClaim:
            claimName: mariadb
