---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: catalog-builder
  namespace: operator-catalog-update
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
- kind: ServiceAccount
  name: catalog-builder
  namespace: operator-catalog-update
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: catalog-builder
  namespace: operator-catalog-update
