---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
  name: cluster-gitops-kustomize
spec:
  generators:
  - git:
      files:
      - path: 'cluster-config/*/cluster-a/*'
      repoURL: https://your-git-repository.example.com
      revision: HEAD
  syncPolicy: {}
  template:
    metadata:
      name: '{{ path[1] }}'
    spec:
      destination:
        namespace: '{{ path[1] }}'
        server: https://kubernetes.default.svc
      project: default
      source:
        path: '{{ path }}'
        repoURL: https://your-git-repository.example.com 
        targetRevision: HEAD
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        retry:
          limit: -1
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 30m
        syncOptions:
          - CreateNamespace=true
          - SkipDryRunOnMissingResource=true
