---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: conjur-secret-store
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 60
  conditions:
  - namespaces:
    - "external-secrets-operator"
    - "group-sync-operator"
    - "openshift-config"
    - "openshift-ingress"
    - "openshift-gitops"
    - "kube-system"
  provider:
    conjur:
      url: https://conjur.example.com
      caBundle: |
        BASE64_ENCODED_CA_BUNDLE_HERE
      auth:
        apikey:
          account: YOUR_ACCOUNT
          userRef:
            name: conjur-creds
            key: hostid
            namespace: external-secrets-operator
          apiKeyRef:
            name: conjur-creds
            key: apikey
            namespace: external-secrets-operator
