---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: conjur-secret-store
  namespace: some-namespace
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 60
  provider:
    conjur:
      url: https://conjur.example.com
      caBundle: |
        BASE64_ENCODED_CA_BUNDLE_HERE
      auth:
        apikey:
          account: YOUR_ACCOUNT
          userRef:
            name: conjur-creds
            key: hostid
          apiKeyRef:
            name: conjur-creds
            key: apikey
