---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cluster-api-certificate
  namespace: openshift-ingress
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  secretStoreRef:
    name: conjur-secret-store
    kind: ClusterSecretStore # or SecretStore
  target:
    creationPolicy: Orphan
    template:
      type: kubernetes.io/tls
      data:
        tls.crt: | # Should be replaced with your TLS certificate data or use the helper script function "convert-tls-cert" to help you do this
          CERTDATA
        tls.key: | # This data is what is going into your secret vault. Note the helper script function "trim-tls-key" for converting your TLS key to be put into a secret store that doesn't natively support certificate data (or ssh key data)
          -----BEGIN PRIVATE KEY-----
          {{ .password | replace "-----BEGIN PRIVATE KEY----- " "" | replace " -----END PRIVATE KEY-----" "" | replace " " "\n" }}
          -----END PRIVATE KEY-----
  data:
  - secretKey: password
    remoteRef:
      key: pwvault/PATH/YOUR_VAULT/YOUR_SECRET_ACCOUNT_NAME/password
