---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ldap-secret
  namespace: group-sync-operator
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 10
  secretStoreRef:
    name: conjur-secret-store
    kind: ClusterSecretStore # or SecretStore
  target:
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: pwvault/PATH/YOUR_VAULT/YOUR_SECRET_ACCOUNT_NAME/username
  - secretKey: password
    remoteRef:
      key: pwvault/PATH/YOUR_VAULT/YOUR_SECRET_ACCOUNT_NAME/password
