---
name: minecraft-server_build

on:
  push:
    branches: [ dockerdev ]
    paths:
      - minecraft/**

env:
  IMAGE_NAME: minecraft-server
  REGISTRY: quay.io

jobs:
  publish:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # https://github.com/docker/login-action
      - name: Log into Quay Container Registry
        uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_PASS }}

      - name: Build Image
        run: |
          cd code-server
          docker build -t ${{ env.REGISTRY }}/${{ secrets.QUAY_USER }}/${{ env.IMAGE_NAME }} .

      - name: Push Image
        run: |
          docker push ${{ env.REGISTRY }}/${{ secrets.QUAY_USER }}/${{ env.IMAGE_NAME }}:latest
