---
- name: Validate Groups
  group:
    name: "{{ item }}"
    state: present
  loop: "{{ custom_groups }}"

- name: Add new User
  user:
    name: "{{ item }}"
    shell: /bin/bash
    groups: operations, developers
    append: yes
  loop: "{{ custom_users }}"

- name: Generate SSH key for new user
  user:
    name: "{{ item }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  loop: "{{ custom_users }}"

- name: Set ssh auth key
  authorized_key:
    user: "{{ item }}"
    state: present
    key: "{{ lookup('file', '/Users/kylewalker/.ssh/id_rsa.pub') }}"
  loop: "{{ custom_users }}"
